### PR TITLE
Add tools/netwatch exporter

### PR DESCRIPTION
**Pull request by valer-cara**
Resolves https://github.com/nshttpd/mikrotik-exporter/issues/84

Add exporter for tools/netwatch. Value mapping is:
- `1`: up
- `0`: unknown
- `-1`: down

### CODE REVIEW

**Comment by vsrod** [comment]
Please add these changes, i need netwatch monitoring in my project.

**Comment by nshttpd** [comment]
@valer-cara if you can pull from master and rebase your branch for the PR I'll get it merged in for @vsrod ..

**Comment by valer-cara** [comment]
@nshttpd - it's ready

**Comment by nshttpd** [comment]
@valer-cara thanks. It's merged.

@vsrod you can grab the 1.0.12-DEVEL build to see if this works for you. I'll cut a real 1.0.12 build sometime this week.

**Pull request merged**
